// <auto-generated />
using System;
using MediaCloud.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaCloud.Domain.Migrations
{
    [DbContext(typeof(MediaCloudContext))]
    [Migration("20180527134300_AddedSeasonPosterPath")]
    partial class AddedSeasonPosterPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("MediaCloud.Domain.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EpisodeNumber");

                    b.Property<int?>("SeasonId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BackdropPath");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("PosterPath");

                    b.Property<DateTime?>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.ItemGenre", b =>
                {
                    b.Property<int>("ItemId");

                    b.Property<int>("GenreId");

                    b.HasKey("ItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ItemGenres");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.ItemLibrary", b =>
                {
                    b.Property<int>("ItemId");

                    b.Property<int>("LibraryId");

                    b.HasKey("ItemId", "LibraryId");

                    b.HasIndex("LibraryId");

                    b.ToTable("ItemLibraries");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Library");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EpisodeId");

                    b.Property<string>("FileLocation");

                    b.Property<int?>("LibraryId");

                    b.Property<int?>("MovieId");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MovieId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PosterPath");

                    b.Property<int>("SeasonNumber");

                    b.Property<int?>("SeriesId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Movie", b =>
                {
                    b.HasBaseType("MediaCloud.Domain.Entities.Item");


                    b.ToTable("Movie");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Series", b =>
                {
                    b.HasBaseType("MediaCloud.Domain.Entities.Item");


                    b.ToTable("Series");

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.MovieLibrary", b =>
                {
                    b.HasBaseType("MediaCloud.Domain.Entities.Library");


                    b.ToTable("MovieLibrary");

                    b.HasDiscriminator().HasValue("MovieLibrary");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.SeriesLibrary", b =>
                {
                    b.HasBaseType("MediaCloud.Domain.Entities.Library");


                    b.ToTable("SeriesLibrary");

                    b.HasDiscriminator().HasValue("SeriesLibrary");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Episode", b =>
                {
                    b.HasOne("MediaCloud.Domain.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.ItemGenre", b =>
                {
                    b.HasOne("MediaCloud.Domain.Entities.Genre", "Genre")
                        .WithMany("ItemGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaCloud.Domain.Entities.Item", "Item")
                        .WithMany("ItemGenres")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.ItemLibrary", b =>
                {
                    b.HasOne("MediaCloud.Domain.Entities.Item", "Item")
                        .WithMany("ItemLibraries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaCloud.Domain.Entities.Library", "Library")
                        .WithMany("ItemLibraries")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Media", b =>
                {
                    b.HasOne("MediaCloud.Domain.Entities.Episode", "Episode")
                        .WithMany("Media")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MediaCloud.Domain.Entities.Library", "Library")
                        .WithMany("Media")
                        .HasForeignKey("LibraryId");

                    b.HasOne("MediaCloud.Domain.Entities.Movie", "Movie")
                        .WithMany("Media")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("MediaCloud.Domain.Entities.Season", b =>
                {
                    b.HasOne("MediaCloud.Domain.Entities.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId");
                });
#pragma warning restore 612, 618
        }
    }
}
